DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Vastuuhenkilo CASCADE;
DROP TABLE IF EXISTS Kurssinvastuu CASCADE;
DROP TABLE IF EXISTS Kysely CASCADE;
DROP TABLE IF EXISTS Laitos CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;